--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Slayer-Return/NetheriteAntiKnockback
build-by-default: true
branches:
- main
projects:
  NetheriteAntiKnockback:
    path: ""
    icon: "armor.png"
...
